Fixes #8 : Broken images
ai-cfia/devops pull request #10
Opened 2023-10-03 21:00 UTC by redat97

changed link to images

2023-10-03 21:17 UTC, rngadam requested changes

2023-10-03 21:17 UTC, rngadam commented on github-repository-creation-guide.md
> +<img width="222" alt="Items" src="https://github.com/ai-cfia/devops/assets/9827730/5b5d85ef-5713-4c60-a519-6602f86e008a">
use relative links and the same markdown format with exclamation point, bracket and parenthesis to insert image

2023-10-04 12:10 UTC, redat97 commented
Fixes #7   : LICENCE vs LICENSE as well

2023-10-05 17:11 UTC, rngadam approved these changes

2023-10-06 14:35 UTC, merged