Adding codeowners file creation script
ai-cfia/devops pull request #32
Opened 2024-02-28 17:01 UTC by SonOfLope

This pull request gives the following : 
- update ruleset for branch protection to require review from code owners
- sh script that creates a CODEOWNERS file in repo's which names end with "backend", "frontend" or "db". Also adds devops teams as code owners for all .github folder and Dockerfiles/docker-compose files across all repositories.

2024-03-01 01:02 UTC, rngadam requested changes
Seems like the repository devops itself is lacking the Github Workflows to lint markdown and would need linter setup for shell scripts.

2024-03-01 20:42 UTC, SonOfLope commented
Shellcheck will be used with the action [shell-linter](https://github.com/marketplace/actions/shell-linter). 
I applied Shellcheck for the current pull request to make sure it passes the check. The following [issue](https://github.com/ai-cfia/github-workflows/issues/99) will add the reusable action workflow.

2024-03-01 20:48 UTC, rngadam requested changes

2024-03-01 20:48 UTC, rngadam commented on github-management-script/codeowners-file-creation.sh
> +done
there's a missing EOF newline here but no error from the Github check. However, repo standards validation is setup and there's a validation of EOF newlines here:

https://github.com/ai-cfia/github-workflows/blob/7fd0e183968b9ea1590d4c4614bd91d61331513f/.github/workflows/workflow-repo-standards-validation.yml#L174

not sure what is going on. I"ve seen this also in another pull request where the checks don't seem to be actually running.

2024-03-01 21:01 UTC, SonOfLope commented
Added sh check workflow. The pipeline wont work for now since we need to wait until the workflow gets merged on [github-workflow. ](https://github.com/ai-cfia/github-workflows/pull/100)

As for the newline, the workflow seems to run but doesnt detect that the file doesnt have new line : 
![image](https://github.com/ai-cfia/devops/assets/73133692/be13d620-436b-4c12-8b46-b0479c3bba0b)
I will investigate.

2024-03-04 16:58 UTC, rngadam commented
> I will investigate.

Suggest referencing the issue into which the investigation / fix is being done. Also good place to use "Reference in new issue".

2024-03-04 16:58 UTC, rngadam approved these changes
see comment on linking to related issues.

2024-03-04 20:58 UTC, merged